services:
  backend:
    build: ./bookstore-api
    container_name: bookstore-api
    env_file:
      - ./bookstore-api/.env
    ports:
      - "8000:8000"
    volumes:
      - ./bookstore-api:/app
    restart: unless-stopped
    networks:
      - app-network

  # frontend:
  #   build: ./bookstore-react
  #   container_name: bookstore-react
  #   env_file:
  #     - ./bookstore-react/.env
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./bookstore-react:/app
  #   stdin_open: true
  #   tty: true
  #   restart: unless-stopped
  #   networks:
  #     - app-network

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
