version: "3.9"
services:
  api:
    build: .
    container_name: bookstore-api
    env_file: .env
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
