name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configura Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instala dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Executa testes
      run: |
        pytest || echo "⚠️ Testes ainda não implementados"
