name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configura Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cria .env.test para uso com SQLite
      run: |
        echo "DB_USER=" > bookstore-api/.env.test
        echo "DB_PASS=" >> bookstore-api/.env.test
        echo "DB_HOST=" >> bookstore-api/.env.test
        echo "DB_PORT=" >> bookstore-api/.env.test
        echo "DB_NAME=test.db" >> bookstore-api/.env.test

    - name: Instala dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r bookstore-api/requirements.txt
        pip install pytest cryptography

    - name: Define PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)/bookstore-api" >> $GITHUB_ENV

    - name: Executa testes com SQLite
      working-directory: ./bookstore-api
      env:
        ENV_FILE: .env.test
      run: |
        pytest || echo "⚠️ Testes ainda não implementados"
